"""
tool_registry.py — Static registry of all benchmark tools.

This module defines TOOL_REGISTRY, an ordered list of ToolEntry objects
covering every tool, backend, and fallback the system knows about.

Rules:
  - Each entry has a unique ``id``.
  - Fallback tools set ``fallback_for`` to the id of the primary they back.
  - The order within a domain is: primary first, then fallbacks in preference
    order.
  - This module is pure data — no I/O, no subprocess calls.
"""

from __future__ import annotations

from app.core.schemas import (
    CredibilityLevel,
    DetectionMethod,
    Domain,
    Role,
    Tier,
    ToolEntry,
)

# ---------------------------------------------------------------------------
# CPU
# ---------------------------------------------------------------------------

_CPU: list[ToolEntry] = [
    ToolEntry(
        id="sysbench-cpu",
        display_name="sysbench CPU",
        domain=Domain.CPU,
        purpose="Multi-threaded CPU integer benchmark using prime-number computation.",
        role=Role.PRIMARY,
        tier=Tier.REQUIRED,
        binary="sysbench",
        detection_method=DetectionMethod.WHICH,
        version_flag="--version",
        supported_modes=["single-thread", "multi-thread"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["events_per_second", "latency_avg_ms", "latency_95p_ms"],
        credibility=CredibilityLevel.HIGH,
        apt_package="sysbench",
        gui_toggle=True,
        diagnostic_fields=["version", "installed", "binary_path", "thread_count"],
        notes="Industry standard for quick CPU comparisons.",
    ),
    ToolEntry(
        id="stress-ng-cpu",
        display_name="stress-ng CPU",
        domain=Domain.CPU,
        purpose="Broad stress test with many CPU stressors; used as fallback and thermal probe.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="stress-ng",
        detection_method=DetectionMethod.WHICH,
        version_flag="--version",
        supported_modes=["cpu", "matrix", "fft", "bitops"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["bogo_ops", "bogo_ops_per_sec", "wall_clock_s"],
        credibility=CredibilityLevel.MEDIUM,
        apt_package="stress-ng",
        gui_toggle=True,
        fallback_for="sysbench-cpu",
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Wider stressor coverage than sysbench; less comparable across systems.",
    ),
    ToolEntry(
        id="geekbench6-cpu",
        display_name="Geekbench 6",
        domain=Domain.CPU,
        purpose="Industry-recognised single- and multi-core benchmark with global score database.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="geekbench6",
        detection_method=DetectionMethod.WHICH,
        version_flag="--version",
        supported_modes=["single-core", "multi-core"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["single_core_score", "multi_core_score"],
        credibility=CredibilityLevel.HIGH,
        apt_package=None,
        gui_toggle=True,
        fallback_for="sysbench-cpu",
        env_constraints=["requires internet for score upload (optional)", "proprietary binary"],
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Proprietary; not in apt. Download from primate-labs.com.",
    ),
]

# ---------------------------------------------------------------------------
# GPU
# ---------------------------------------------------------------------------

_GPU: list[ToolEntry] = [
    ToolEntry(
        id="glmark2",
        display_name="glmark2",
        domain=Domain.GPU,
        purpose="OpenGL 2.0 benchmark suite covering geometry, lighting, textures, and composition.",
        role=Role.PRIMARY,
        tier=Tier.REQUIRED,
        binary="glmark2",
        detection_method=DetectionMethod.WHICH,
        version_flag="--version",
        supported_modes=["default", "offscreen", "wayland", "drm"],
        safe_headless=False,
        safe_offscreen=True,
        output_metrics=["score", "fps_per_scene"],
        credibility=CredibilityLevel.HIGH,
        apt_package="glmark2",
        gui_toggle=True,
        env_constraints=["requires OpenGL >= 2.0", "requires display or offscreen context"],
        diagnostic_fields=["version", "installed", "binary_path", "opengl_renderer", "opengl_version"],
        notes="Use --offscreen for headless CI runs.",
    ),
    ToolEntry(
        id="glxgears",
        display_name="glxgears",
        domain=Domain.GPU,
        purpose="Minimal OpenGL smoke test; confirms driver stack is functional.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="glxgears",
        detection_method=DetectionMethod.WHICH,
        version_flag="-info",
        supported_modes=["default"],
        safe_headless=False,
        safe_offscreen=True,
        output_metrics=["fps"],
        credibility=CredibilityLevel.LOW,
        apt_package="mesa-utils",
        gui_toggle=True,
        fallback_for="glmark2",
        env_constraints=["requires DISPLAY or Xvfb"],
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Not a rigorous benchmark; useful only as a driver sanity check.",
    ),
    ToolEntry(
        id="vkmark",
        display_name="vkmark",
        domain=Domain.GPU,
        purpose="Vulkan equivalent of glmark2; scores GPU Vulkan performance.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="vkmark",
        detection_method=DetectionMethod.WHICH,
        version_flag="--version",
        supported_modes=["default", "offscreen"],
        safe_headless=False,
        safe_offscreen=True,
        output_metrics=["score", "fps_per_scene"],
        credibility=CredibilityLevel.HIGH,
        apt_package="vkmark",
        gui_toggle=True,
        fallback_for="glmark2",
        env_constraints=["requires Vulkan ICD", "Vulkan >= 1.0"],
        diagnostic_fields=["version", "installed", "binary_path", "vulkan_device"],
        notes="Preferred when target system is Vulkan-first.",
    ),
]

# ---------------------------------------------------------------------------
# Memory
# ---------------------------------------------------------------------------

_MEMORY: list[ToolEntry] = [
    ToolEntry(
        id="sysbench-memory",
        display_name="sysbench Memory",
        domain=Domain.MEMORY,
        purpose="Sequential memory read/write throughput benchmark.",
        role=Role.PRIMARY,
        tier=Tier.REQUIRED,
        binary="sysbench",
        detection_method=DetectionMethod.WHICH,
        version_flag="--version",
        supported_modes=["read", "write"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["throughput_mib_s", "latency_avg_ms"],
        credibility=CredibilityLevel.HIGH,
        apt_package="sysbench",
        gui_toggle=True,
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Shares the sysbench binary with the CPU domain.",
    ),
    ToolEntry(
        id="memtester",
        display_name="memtester",
        domain=Domain.MEMORY,
        purpose="Walks a memory region with destructive tests to detect faults.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="memtester",
        detection_method=DetectionMethod.WHICH,
        version_flag="",
        supported_modes=["fault-detection"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["pass", "fail_count"],
        credibility=CredibilityLevel.MEDIUM,
        apt_package="memtester",
        gui_toggle=True,
        fallback_for="sysbench-memory",
        env_constraints=["may require elevated privileges for large allocations"],
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Diagnostic tool rather than a throughput benchmark.",
    ),
    ToolEntry(
        id="stream-benchmark",
        display_name="STREAM",
        domain=Domain.MEMORY,
        purpose="De-facto standard for sustainable memory bandwidth (Copy/Scale/Add/Triad).",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="stream_c",
        detection_method=DetectionMethod.WHICH,
        version_flag="",
        supported_modes=["copy", "scale", "add", "triad"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["copy_mb_s", "scale_mb_s", "add_mb_s", "triad_mb_s"],
        credibility=CredibilityLevel.HIGH,
        apt_package=None,
        gui_toggle=True,
        fallback_for="sysbench-memory",
        diagnostic_fields=["installed", "binary_path"],
        notes="Must be compiled from source (http://www.cs.virginia.edu/stream/).",
    ),
]

# ---------------------------------------------------------------------------
# Disk / Storage
# ---------------------------------------------------------------------------

_DISK: list[ToolEntry] = [
    ToolEntry(
        id="fio",
        display_name="fio",
        domain=Domain.DISK,
        purpose="Flexible I/O tester covering sequential/random read/write at configurable depths.",
        role=Role.PRIMARY,
        tier=Tier.REQUIRED,
        binary="fio",
        detection_method=DetectionMethod.WHICH,
        version_flag="--version",
        supported_modes=["seq-read", "seq-write", "rand-read", "rand-write", "mixed"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["read_iops", "write_iops", "read_bw_mib_s", "write_bw_mib_s",
                        "lat_avg_us", "lat_99p_us"],
        credibility=CredibilityLevel.HIGH,
        apt_package="fio",
        gui_toggle=True,
        env_constraints=["avoid running on system root unless target device specified"],
        diagnostic_fields=["version", "installed", "binary_path", "target_device"],
        notes="Industry standard for storage benchmarking.",
    ),
    ToolEntry(
        id="iozone",
        display_name="IOzone",
        domain=Domain.DISK,
        purpose="Filesystem benchmark covering a wide matrix of record and file sizes.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="iozone",
        detection_method=DetectionMethod.WHICH,
        version_flag="-v",
        supported_modes=["write", "rewrite", "read", "reread", "random-read", "random-write"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["write_kb_s", "rewrite_kb_s", "read_kb_s", "reread_kb_s"],
        credibility=CredibilityLevel.MEDIUM,
        apt_package="iozone3",
        gui_toggle=True,
        fallback_for="fio",
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Good for filesystem-level analysis; less flexible than fio.",
    ),
    ToolEntry(
        id="hdparm",
        display_name="hdparm",
        domain=Domain.DISK,
        purpose="Simple cached and direct-read throughput probe for block devices.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="hdparm",
        detection_method=DetectionMethod.WHICH,
        version_flag="-V",
        supported_modes=["cached-read", "direct-read"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["buffered_read_mb_s", "disk_read_mb_s"],
        credibility=CredibilityLevel.LOW,
        apt_package="hdparm",
        gui_toggle=True,
        fallback_for="fio",
        env_constraints=["requires root for direct-read mode"],
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Quick smoke test; not a substitute for fio.",
    ),
]

# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------

_NETWORK: list[ToolEntry] = [
    ToolEntry(
        id="iperf3",
        display_name="iperf3",
        domain=Domain.NETWORK,
        purpose="TCP/UDP throughput measurement between two endpoints.",
        role=Role.PRIMARY,
        tier=Tier.REQUIRED,
        binary="iperf3",
        detection_method=DetectionMethod.WHICH,
        version_flag="--version",
        supported_modes=["tcp", "udp", "bidirectional"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["throughput_mbits_s", "retransmits", "jitter_ms", "packet_loss_pct"],
        credibility=CredibilityLevel.HIGH,
        apt_package="iperf3",
        gui_toggle=True,
        env_constraints=["requires iperf3 server on remote host"],
        diagnostic_fields=["version", "installed", "binary_path", "server_reachable"],
        notes="Measures LAN/WAN throughput; needs a cooperating server.",
    ),
    ToolEntry(
        id="speedtest-cli",
        display_name="Speedtest CLI",
        domain=Domain.NETWORK,
        purpose="ISP-grade internet speed test against Ookla CDN nodes.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="speedtest",
        detection_method=DetectionMethod.WHICH,
        version_flag="--version",
        supported_modes=["download", "upload", "latency"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["download_mbits_s", "upload_mbits_s", "latency_ms"],
        credibility=CredibilityLevel.MEDIUM,
        apt_package=None,
        pip_package="speedtest-cli",
        gui_toggle=True,
        fallback_for="iperf3",
        env_constraints=["requires internet access"],
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Results vary by ISP conditions; not suitable for LAN benchmarking.",
    ),
    ToolEntry(
        id="netperf",
        display_name="netperf",
        domain=Domain.NETWORK,
        purpose="TCP stream and request/response benchmark for detailed latency profiling.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="netperf",
        detection_method=DetectionMethod.WHICH,
        version_flag="-V",
        supported_modes=["TCP_STREAM", "TCP_RR", "UDP_STREAM", "UDP_RR"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["throughput_mbits_s", "mean_latency_us"],
        credibility=CredibilityLevel.HIGH,
        apt_package="netperf",
        gui_toggle=True,
        fallback_for="iperf3",
        env_constraints=["requires netserver running on remote host"],
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Preferred for latency-sensitive profiling (RR test).",
    ),
]

# ---------------------------------------------------------------------------
# General / Cross-domain
# ---------------------------------------------------------------------------

_GENERAL: list[ToolEntry] = [
    ToolEntry(
        id="phoronix-test-suite",
        display_name="Phoronix Test Suite",
        domain=Domain.GENERAL,
        purpose="Comprehensive multi-domain benchmark framework with OpenBenchmarking.org upload.",
        role=Role.PRIMARY,
        tier=Tier.OPTIONAL,
        binary="phoronix-test-suite",
        detection_method=DetectionMethod.WHICH,
        version_flag="version",
        supported_modes=["cpu", "gpu", "disk", "memory", "composite"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["composite_score", "per_suite_score"],
        credibility=CredibilityLevel.HIGH,
        apt_package="phoronix-test-suite",
        gui_toggle=True,
        env_constraints=["downloads test suites on first run (~100 MB+)", "needs internet for download"],
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Opinionated suite runner; useful for full-system regression tracking.",
    ),
    ToolEntry(
        id="wrk-http",
        display_name="wrk HTTP",
        domain=Domain.GENERAL,
        purpose="HTTP load generator for measuring web server throughput and latency.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="wrk",
        detection_method=DetectionMethod.WHICH,
        version_flag="--version",
        supported_modes=["http", "https"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["requests_per_sec", "latency_avg_ms", "latency_99p_ms", "transfer_mb_s"],
        credibility=CredibilityLevel.HIGH,
        apt_package=None,
        gui_toggle=True,
        fallback_for="phoronix-test-suite",
        env_constraints=["requires a target HTTP endpoint"],
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Not in apt; compile from https://github.com/wg/wrk.",
    ),
    ToolEntry(
        id="ab-http",
        display_name="Apache Bench (ab)",
        domain=Domain.GENERAL,
        purpose="Single-connection HTTP benchmark; quick smoke test for web endpoints.",
        role=Role.FALLBACK,
        tier=Tier.OPTIONAL,
        binary="ab",
        detection_method=DetectionMethod.WHICH,
        version_flag="-V",
        supported_modes=["http"],
        safe_headless=True,
        safe_offscreen=True,
        output_metrics=["requests_per_sec", "time_per_request_ms", "failed_requests"],
        credibility=CredibilityLevel.LOW,
        apt_package="apache2-utils",
        gui_toggle=True,
        fallback_for="wrk-http",
        diagnostic_fields=["version", "installed", "binary_path"],
        notes="Simpler than wrk; single-threaded; not suitable for high-concurrency tests.",
    ),
]

# ---------------------------------------------------------------------------
# Assembled registry
# ---------------------------------------------------------------------------

TOOL_REGISTRY: list[ToolEntry] = _CPU + _GPU + _MEMORY + _DISK + _NETWORK + _GENERAL

# Indexed for fast lookup by id
TOOL_REGISTRY_BY_ID: dict[str, ToolEntry] = {t.id: t for t in TOOL_REGISTRY}
